# permissions for end users to view cloudsqlinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sledge-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudsqlinstance-viewer-role
rules:
- apiGroups:
  - cloudsql.uipath.studio
  resources:
  - cloudsqlinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudsql.uipath.studio
  resources:
  - cloudsqlinstances/status
  verbs:
  - get
