---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudsql.uipath.studio
  resources:
  - cloudsqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudsql.uipath.studio
  resources:
  - cloudsqlinstances/finalizers
  verbs:
  - update
- apiGroups:
  - cloudsql.uipath.studio
  resources:
  - cloudsqlinstances/status
  verbs:
  - get
  - patch
  - update
